-- VIP Drama Live Center
-- Run this migration once in Supabase SQL Editor.
-- This module is for authorized/licensed live channels and sports events only.

create table if not exists public.vip_live_channels (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'general'
    check (category in ('general','news','sports','entertainment','kids','religious','other')),
  language text default 'ar',
  description text,
  logo_url text,
  stream_url text,
  embed_url text,
  source_url text,
  license_url text,
  rights_holder text,
  territories text default 'Worldwide',
  is_live boolean not null default false,
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vip_live_matches (
  id bigint generated by default as identity primary key,
  league text,
  home_team text not null,
  away_team text not null,
  home_logo text,
  away_logo text,
  status text not null default 'scheduled'
    check (status in ('scheduled','live','halftime','finished','postponed')),
  start_time timestamptz,
  home_score integer not null default 0,
  away_score integer not null default 0,
  minute integer,
  venue text,
  stream_url text,
  embed_url text,
  source_url text,
  license_url text,
  rights_holder text,
  territories text default 'Worldwide',
  possession_home numeric(5,2),
  possession_away numeric(5,2),
  shots_home integer not null default 0,
  shots_away integer not null default 0,
  shots_on_target_home integer not null default 0,
  shots_on_target_away integer not null default 0,
  corners_home integer not null default 0,
  corners_away integer not null default 0,
  yellow_home integer not null default 0,
  yellow_away integer not null default 0,
  red_home integer not null default 0,
  red_away integer not null default 0,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vip_live_channels_public_idx
on public.vip_live_channels(published, sort_order);

create index if not exists vip_live_matches_public_idx
on public.vip_live_matches(published, start_time);

alter table public.vip_live_channels enable row level security;
alter table public.vip_live_matches enable row level security;

revoke all on table public.vip_live_channels from anon, authenticated;
revoke all on table public.vip_live_matches from anon, authenticated;

grant select on public.vip_live_channels to anon, authenticated;
grant select, insert, update, delete on public.vip_live_channels to authenticated;
grant select on public.vip_live_matches to anon, authenticated;
grant select, insert, update, delete on public.vip_live_matches to authenticated;

drop policy if exists "Public can read published live channels" on public.vip_live_channels;
create policy "Public can read published live channels"
on public.vip_live_channels for select
to anon, authenticated
using (published = true);

drop policy if exists "Admins can manage live channels" on public.vip_live_channels;
create policy "Admins can manage live channels"
on public.vip_live_channels for all
to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id=(select auth.uid())))
with check (exists (select 1 from public.vip_admins a where a.user_id=(select auth.uid())));

drop policy if exists "Public can read published live matches" on public.vip_live_matches;
create policy "Public can read published live matches"
on public.vip_live_matches for select
to anon, authenticated
using (published = true);

drop policy if exists "Admins can manage live matches" on public.vip_live_matches;
create policy "Admins can manage live matches"
on public.vip_live_matches for all
to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id=(select auth.uid())))
with check (exists (select 1 from public.vip_admins a where a.user_id=(select auth.uid())));

grant usage, select on sequence public.vip_live_channels_id_seq to authenticated;
grant usage, select on sequence public.vip_live_matches_id_seq to authenticated;


-- Enable Realtime for live channel/match updates when the project uses the standard publication.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='vip_live_channels') then
    alter publication supabase_realtime add table public.vip_live_channels;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='vip_live_matches') then
    alter publication supabase_realtime add table public.vip_live_matches;
  end if;
exception when undefined_object then
  null;
end $$;
