-- VIP Drama: Rights-first content request queue
-- This table keeps unverified titles out of the public catalog until an admin
-- confirms a license, permission, public-domain status, or open-license source.

create table if not exists public.vip_rights_requests (
  id bigint generated by default as identity primary key,
  title text not null,
  production_year integer,
  content_type text not null default 'series'
    check (content_type in ('movie','series','anime','theater','other')),
  origin_country text,
  collection text,
  rights_status text not null default 'pending'
    check (rights_status in ('pending','needs_proof','verified','rejected')),
  rights_holder text,
  source_url text,
  license_url text,
  territories text default 'Worldwide',
  notes text,
  requested_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.vip_rights_requests enable row level security;

revoke all on table public.vip_rights_requests from anon, authenticated;

grant select, insert, update, delete on table public.vip_rights_requests to authenticated;

drop policy if exists "rights_requests_admin_all" on public.vip_rights_requests;
create policy "rights_requests_admin_all"
on public.vip_rights_requests
for all
to authenticated
using (
  exists (
    select 1
    from public.vip_admins a
    where a.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.vip_admins a
    where a.user_id = auth.uid()
  )
);

create index if not exists vip_rights_requests_status_idx
  on public.vip_rights_requests(rights_status);

create index if not exists vip_rights_requests_title_idx
  on public.vip_rights_requests(title);

create index if not exists vip_rights_requests_created_at_idx
  on public.vip_rights_requests(created_at desc);

comment on table public.vip_rights_requests is
  'Rights-first queue for titles awaiting proof of permission, license, or public/open-license status.';

comment on column public.vip_rights_requests.rights_status is
  'pending/needs_proof/verified/rejected. Only verified rights should be published to vip_content.';
