-- VIP Drama Supabase database
create table if not exists public.vip_content (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('movie','series','anime')),
  year integer,
  genre text,
  rating numeric(3,1) default 0,
  tag text default 'جديد',
  description text,
  poster text,
  watch_url text,
  video_url text,
  embed_url text,
  license text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vip_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.vip_content enable row level security;
alter table public.vip_admins enable row level security;

revoke all on table public.vip_content from anon, authenticated;
revoke all on table public.vip_admins from anon, authenticated;
grant select on public.vip_content to anon, authenticated;
grant insert, update, delete on public.vip_content to authenticated;
grant select on public.vip_admins to authenticated;

drop policy if exists "Public can read VIP content" on public.vip_content;
create policy "Public can read VIP content" on public.vip_content for select to anon, authenticated using (true);

drop policy if exists "Admins can insert VIP content" on public.vip_content;
create policy "Admins can insert VIP content" on public.vip_content for insert to authenticated
with check (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can update VIP content" on public.vip_content;
create policy "Admins can update VIP content" on public.vip_content for update to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can delete VIP content" on public.vip_content;
create policy "Admins can delete VIP content" on public.vip_content for delete to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can read admin list" on public.vip_admins;
create policy "Admins can read admin list" on public.vip_admins for select to authenticated
using (user_id = (select auth.uid()));

grant usage, select on sequence public.vip_content_id_seq to authenticated;


-- Seed the open/licensed demo library. Re-running this file will not duplicate these titles.
insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,video_url,license,source)
select 'Big Buck Bunny','movie',2008,'رسوم متحركة',8.1,'مرخّص CC','فيلم رسوم متحركة قصير من Blender Foundation، متاح لإعادة الاستخدام وفق CC BY مع متطلبات النسب.','linear-gradient(145deg,#14532d,#f59e0b)','https://video.blender.org/static/webseed/bf1f3fb5-b119-4f9f-9930-8e20e892b898-720.mp4','Creative Commons Attribution 3.0','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Big Buck Bunny');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Sintel','movie',2010,'فانتازيا • رسوم متحركة',8.0,'مرخّص CC','فيلم قصير مفتوح من Blender Foundation، مرخّص للمشاركة والعرض مع الالتزام بالنسب والاعتمادات.','linear-gradient(145deg,#172554,#7c3aed)','https://durian.blender.org/','Creative Commons Attribution 3.0','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Sintel');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Elephants Dream','movie',2006,'خيال • رسوم متحركة',7.8,'مرخّص CC','أحد مشاريع Blender Open Movie، منشور بموجب ترخيص Creative Commons Attribution.','linear-gradient(145deg,#3f1d0b,#ea580c)','https://orange.blender.org/','Creative Commons Attribution','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Elephants Dream');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Tears of Steel','movie',2012,'خيال علمي',7.7,'مرخّص مفتوح','فيلم مفتوح من Blender Institute؛ راجع شروط كل مادة قبل إعادة الاستخدام.','linear-gradient(145deg,#082f49,#0891b2)','https://mango.blender.org/','Creative Commons (راجع صفحة المشروع)','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Tears of Steel');
