-- VIP Drama Supabase database
create table if not exists public.vip_content (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('movie','series','anime')),
  year integer,
  genre text,
  rating numeric(3,1) default 0,
  tag text default 'جديد',
  description text,
  poster text,
  watch_url text,
  video_url text,
  embed_url text,
  license text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vip_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.vip_content enable row level security;
alter table public.vip_admins enable row level security;

revoke all on table public.vip_content from anon, authenticated;
revoke all on table public.vip_admins from anon, authenticated;
grant select on public.vip_content to anon, authenticated;
grant insert, update, delete on public.vip_content to authenticated;
grant select on public.vip_admins to authenticated;

drop policy if exists "Public can read VIP content" on public.vip_content;
create policy "Public can read VIP content" on public.vip_content for select to anon, authenticated using (true);

drop policy if exists "Admins can insert VIP content" on public.vip_content;
create policy "Admins can insert VIP content" on public.vip_content for insert to authenticated
with check (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can update VIP content" on public.vip_content;
create policy "Admins can update VIP content" on public.vip_content for update to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can delete VIP content" on public.vip_content;
create policy "Admins can delete VIP content" on public.vip_content for delete to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can read admin list" on public.vip_admins;
create policy "Admins can read admin list" on public.vip_admins for select to authenticated
using (user_id = (select auth.uid()));

grant usage, select on sequence public.vip_content_id_seq to authenticated;


-- Seed the open/licensed demo library. Re-running this file will not duplicate these titles.
insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,video_url,license,source)
select 'Big Buck Bunny','movie',2008,'رسوم متحركة',8.1,'مرخّص CC','فيلم رسوم متحركة قصير من Blender Foundation، متاح لإعادة الاستخدام وفق CC BY مع متطلبات النسب.','linear-gradient(145deg,#14532d,#f59e0b)','https://video.blender.org/static/webseed/bf1f3fb5-b119-4f9f-9930-8e20e892b898-720.mp4','Creative Commons Attribution 3.0','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Big Buck Bunny');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Sintel','movie',2010,'فانتازيا • رسوم متحركة',8.0,'مرخّص CC','فيلم قصير مفتوح من Blender Foundation، مرخّص للمشاركة والعرض مع الالتزام بالنسب والاعتمادات.','linear-gradient(145deg,#172554,#7c3aed)','https://durian.blender.org/','Creative Commons Attribution 3.0','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Sintel');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Elephants Dream','movie',2006,'خيال • رسوم متحركة',7.8,'مرخّص CC','أحد مشاريع Blender Open Movie، منشور بموجب ترخيص Creative Commons Attribution.','linear-gradient(145deg,#3f1d0b,#ea580c)','https://orange.blender.org/','Creative Commons Attribution','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Elephants Dream');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Tears of Steel','movie',2012,'خيال علمي',7.7,'مرخّص مفتوح','فيلم مفتوح من Blender Institute؛ راجع شروط كل مادة قبل إعادة الاستخدام.','linear-gradient(145deg,#082f49,#0891b2)','https://mango.blender.org/','Creative Commons (راجع صفحة المشروع)','Blender Foundation'
where not exists (select 1 from public.vip_content where title='Tears of Steel');


insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Spring','movie',2019,'فانتازيا • رسوم متحركة',0,'مرخّص CC BY 4.0','فيلم رسوم متحركة قصير من Blender Animation Studio، منشور وفق Creative Commons Attribution 4.0 مع متطلبات النسب.','linear-gradient(145deg,#14532d,#84cc16)','https://studio.blender.org/projects/spring/','Creative Commons Attribution 4.0','Blender Studio'
where not exists (select 1 from public.vip_content where title='Spring');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Cosmos Laundromat: First Cycle','movie',2015,'خيال • رسوم متحركة',0,'مفتوح ومرخّص','الحلقة الأولى من مشروع Blender Open Movie، متاحة للمشاركة وإعادة المزج وفق الترخيص المعلن للمشروع.','linear-gradient(145deg,#312e81,#f97316)','https://studio.blender.org/projects/cosmos-laundromat/','Creative Commons / permissive license حسب مادة المشروع','Blender Studio'
where not exists (select 1 from public.vip_content where title='Cosmos Laundromat: First Cycle');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Charge','movie',2022,'خيال علمي • أكشن',0,'مرخّص CC BY 4.0','فيلم Blender Open Movie قصير في عالم مستقبلي يعاني من نقص الطاقة؛ محتوى Blender Studio الرقمي متاح عمومًا وفق CC BY ما لم يذكر خلاف ذلك.','linear-gradient(145deg,#111827,#dc2626)','https://studio.blender.org/projects/charge/','Creative Commons Attribution 4.0 (ما لم يذكر خلاف ذلك)','Blender Studio'
where not exists (select 1 from public.vip_content where title='Charge');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Sprite Fright','movie',2021,'رعب كوميدي • رسوم متحركة',0,'مرخّص CC BY','فيلم Blender Open Movie بطابع رعب كوميدي، ومشروعه منشور وفق Creative Commons Attribution مع استثناءات موضحة في صفحة الترخيص.','linear-gradient(145deg,#3f0d12,#16a34a)','https://studio.blender.org/projects/sprite-fright/','Creative Commons Attribution 1.0','Blender Studio'
where not exists (select 1 from public.vip_content where title='Sprite Fright');

insert into public.vip_content (title,type,year,genre,rating,tag,description,poster,embed_url,license,source)
select 'Wing It!','movie',2023,'كوميديا • رسوم متحركة',0,'مرخّص CC BY 4.0','فيلم Blender Open Movie قصير؛ صفحة الترخيص الرسمية تسمح بإعادة الاستخدام والتوزيع مع النسب.','linear-gradient(145deg,#0f172a,#f59e0b)','https://studio.blender.org/projects/wing-it/','Creative Commons Attribution 4.0','Blender Studio'
where not exists (select 1 from public.vip_content where title='Wing It!');

-- Privacy-friendly view counter: no IP address is stored.
alter table public.vip_content
  add column if not exists view_count bigint not null default 0;

create or replace function public.record_view(p_content_id bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_count bigint;
begin
  update public.vip_content
  set view_count = view_count + 1,
      updated_at = now()
  where id = p_content_id
  returning view_count into new_count;
  return coalesce(new_count, 0);
end;
$$;

revoke execute on function public.record_view(bigint) from public;
grant execute on function public.record_view(bigint) to anon, authenticated;


-- Re-run-safe repair for previously seeded rows.
-- The standalone migration supabase/repair_catalog.sql contains the same repair for an existing project.
update public.vip_content set video_url='https://video.blender.org/static/webseed/bf1f3fb5-b119-4f9f-9930-8e20e892b898-720.mp4',embed_url='https://video.blender.org/videos/embed/bf1f3fb5-b119-4f9f-9930-8e20e892b898',updated_at=now() where title='Big Buck Bunny';
update public.vip_content set video_url='https://video.blender.org/static/webseed/0eb052d0-fd51-43e6-aa33-ecdbf77a5d40-720.mp4',embed_url='https://video.blender.org/videos/embed/0eb052d0-fd51-43e6-aa33-ecdbf77a5d40',updated_at=now() where title='Sintel';
update public.vip_content set video_url='https://video.blender.org/static/webseed/cccc3e60-0291-4ecc-aa56-39b2e2c7d0d5-720.mp4',embed_url='https://video.blender.org/videos/embed/cccc3e60-0291-4ecc-aa56-39b2e2c7d0d5',updated_at=now() where title='Elephants Dream';
update public.vip_content set video_url='https://video.blender.org/static/webseed/8533ea43-4271-4a57-9694-e9d0b35e1aa1-720.mp4',embed_url='https://video.blender.org/videos/embed/8533ea43-4271-4a57-9694-e9d0b35e1aa1',updated_at=now() where title='Tears of Steel';
update public.vip_content set video_url='https://video.blender.org/static/webseed/3d95fb3d-c866-42c8-9db1-fe82f48ccb95-720.mp4',embed_url='https://video.blender.org/videos/embed/3d95fb3d-c866-42c8-9db1-fe82f48ccb95',updated_at=now() where title='Spring';
update public.vip_content set video_url=null,embed_url='https://video.blender.org/videos/embed/09f77c81-7b1b-483a-9d46-b14f2078c604',updated_at=now() where title='Charge';
update public.vip_content set video_url='https://video.blender.org/download/videos/a69d68a5-a0e0-4a80-9d66-49f093c97aaf-720.mp4',embed_url='https://video.blender.org/videos/embed/a69d68a5-a0e0-4a80-9d66-49f093c97aaf',updated_at=now() where title='Sprite Fright';
update public.vip_content set video_url=null,embed_url='https://video.blender.org/videos/embed/bd0084a5-1d26-4816-ab5e-1bad9e2fb990',updated_at=now() where title='Wing It!';
update public.vip_content set video_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/CaptainVideo1949.ogv',embed_url=null,updated_at=now() where title='Captain Video – Episode';
update public.vip_content set video_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/001-Felix-the-Cat-S01E01-The-Magic-Bag.webm',embed_url=null,updated_at=now() where title='Felix the Cat – The Magic Bag';
delete from public.vip_content where title='Cosmos Laundromat: First Cycle';