-- VIP Drama Supabase database
create table if not exists public.vip_content (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('movie','series','anime')),
  year integer,
  genre text,
  rating numeric(3,1) default 0,
  tag text default 'جديد',
  description text,
  poster text,
  watch_url text,
  video_url text,
  embed_url text,
  license text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vip_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.vip_content enable row level security;
alter table public.vip_admins enable row level security;

revoke all on table public.vip_content from anon, authenticated;
revoke all on table public.vip_admins from anon, authenticated;
grant select on public.vip_content to anon, authenticated;
grant insert, update, delete on public.vip_content to authenticated;
grant select on public.vip_admins to authenticated;

drop policy if exists "Public can read VIP content" on public.vip_content;
create policy "Public can read VIP content" on public.vip_content for select to anon, authenticated using (true);

drop policy if exists "Admins can insert VIP content" on public.vip_content;
create policy "Admins can insert VIP content" on public.vip_content for insert to authenticated
with check (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can update VIP content" on public.vip_content;
create policy "Admins can update VIP content" on public.vip_content for update to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())))
with check (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can delete VIP content" on public.vip_content;
create policy "Admins can delete VIP content" on public.vip_content for delete to authenticated
using (exists (select 1 from public.vip_admins a where a.user_id = (select auth.uid())));

drop policy if exists "Admins can read admin list" on public.vip_admins;
create policy "Admins can read admin list" on public.vip_admins for select to authenticated
using (user_id = (select auth.uid()));

grant usage, select on sequence public.vip_content_id_seq to authenticated;
