-- VIP Drama: Professional Series Seasons & Episodes
-- Run this migration once in Supabase SQL Editor.
-- It creates seasons/episodes, protects them with RLS, and lets public users
-- read only episodes belonging to published titles.

create table if not exists public.vip_seasons (
  id bigint generated by default as identity primary key,
  content_id bigint not null references public.vip_content(id) on delete cascade,
  season_number integer not null check (season_number > 0),
  title text,
  description text,
  poster text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(content_id, season_number)
);

create table if not exists public.vip_episodes (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.vip_seasons(id) on delete cascade,
  episode_number integer not null check (episode_number > 0),
  title text not null,
  description text,
  video_url text,
  embed_url text,
  watch_url text,
  license text,
  source text,
  license_url text,
  rights_holder text,
  territories text default 'Worldwide',
  published boolean not null default true,
  duration_seconds integer,
  poster text,
  view_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season_id, episode_number)
);

create index if not exists vip_seasons_content_idx
on public.vip_seasons(content_id, season_number);

create index if not exists vip_episodes_season_idx
on public.vip_episodes(season_id, episode_number);

create index if not exists vip_episodes_published_idx
on public.vip_episodes(published);

alter table public.vip_seasons enable row level security;
alter table public.vip_episodes enable row level security;

revoke all on table public.vip_seasons from anon, authenticated;
revoke all on table public.vip_episodes from anon, authenticated;

grant select on public.vip_seasons to anon, authenticated;
grant select, insert, update, delete on public.vip_seasons to authenticated;
grant select on public.vip_episodes to anon, authenticated;
grant select, insert, update, delete on public.vip_episodes to authenticated;

drop policy if exists "Public can read published series seasons" on public.vip_seasons;
create policy "Public can read published series seasons"
on public.vip_seasons
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.vip_content c
    where c.id = vip_seasons.content_id
      and c.type = 'series'
      and c.published = true
  )
);

drop policy if exists "Admins can manage seasons" on public.vip_seasons;
create policy "Admins can manage seasons"
on public.vip_seasons
for all
to authenticated
using (
  exists (
    select 1 from public.vip_admins a
    where a.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.vip_admins a
    where a.user_id = (select auth.uid())
  )
);

drop policy if exists "Public can read published series episodes" on public.vip_episodes;
create policy "Public can read published series episodes"
on public.vip_episodes
for select
to anon, authenticated
using (
  vip_episodes.published = true
  and exists (
    select 1
    from public.vip_seasons s
    join public.vip_content c on c.id = s.content_id
    where s.id = vip_episodes.season_id
      and c.type = 'series'
      and c.published = true
  )
);

drop policy if exists "Admins can manage episodes" on public.vip_episodes;
create policy "Admins can manage episodes"
on public.vip_episodes
for all
to authenticated
using (
  exists (
    select 1 from public.vip_admins a
    where a.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.vip_admins a
    where a.user_id = (select auth.uid())
  )
);

grant usage, select on sequence public.vip_seasons_id_seq to authenticated;
grant usage, select on sequence public.vip_episodes_id_seq to authenticated;

-- Privacy-friendly episode view counter: no IP address is stored.
create or replace function public.record_episode_view(p_episode_id bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_count bigint;
begin
  update public.vip_episodes
  set view_count = view_count + 1,
      updated_at = now()
  where id = p_episode_id
    and published = true
  returning view_count into new_count;

  return coalesce(new_count, 0);
end;
$$;

revoke execute on function public.record_episode_view(bigint) from public;
grant execute on function public.record_episode_view(bigint) to anon, authenticated;
