window.VIP_CONTENT=[
{id:1,title:"Big Buck Bunny",type:"movie",year:2008,genre:"رسوم متحركة",rating:8.1,tag:"مرخّص CC",description:"فيلم رسوم متحركة قصير من Blender Foundation، متاح لإعادة الاستخدام وفق CC BY مع متطلبات النسب.",poster:"linear-gradient(145deg,#14532d,#f59e0b)",watchUrl:"https://video.blender.org/videos/watch/bf1f3fb5-b119-4f9f-9930-8e20e892b898",videoUrl:"https://video.blender.org/static/webseed/bf1f3fb5-b119-4f9f-9930-8e20e892b898-720.mp4",license:"Creative Commons Attribution 3.0",source:"Blender Foundation"},
{id:2,title:"Sintel",type:"movie",year:2010,genre:"فانتازيا • رسوم متحركة",rating:8.0,tag:"مرخّص CC",description:"فيلم قصير مفتوح من Blender Foundation، مرخّص للمشاركة والعرض مع الالتزام بالنسب والاعتمادات.",poster:"linear-gradient(145deg,#172554,#7c3aed)",watchUrl:"https://durian.blender.org/",license:"Creative Commons Attribution 3.0",source:"Blender Foundation"},
{id:3,title:"Elephants Dream",type:"movie",year:2006,genre:"خيال • رسوم متحركة",rating:7.8,tag:"مرخّص CC",description:"أحد مشاريع Blender Open Movie، منشور بموجب ترخيص Creative Commons Attribution.",poster:"linear-gradient(145deg,#3f1d0b,#ea580c)",watchUrl:"https://orange.blender.org/",license:"Creative Commons Attribution",source:"Blender Foundation"},
{id:4,title:"Tears of Steel",type:"movie",year:2012,genre:"خيال علمي",rating:7.7,tag:"مرخّص مفتوح",description:"فيلم مفتوح من Blender Institute مع مواد منشورة وفق تراخيص Creative Commons؛ راجع شروط كل مادة قبل إعادة الاستخدام.",poster:"linear-gradient(145deg,#082f49,#0891b2)",watchUrl:"https://mango.blender.org/",license:"Creative Commons (راجع صفحة المشروع)",source:"Blender Foundation"},
{id:5,title:"Captain Video – Episode",type:"series",year:1949,genre:"خيال علمي • كلاسيكي",rating:7.0,tag:"حلقة Public Domain",description:"حلقة تاريخية من Captain Video and His Video Rangers. حالة حقوق الحلقة المشار إليها موصوفة كمجال عام في مصادر الأرشيف، ويجب التحقق من حقوق أي عناصر مرافقة.",poster:"linear-gradient(145deg,#111827,#2563eb)",watchUrl:"https://archive.org/details/captain-video-and-his-video-rangers",license:"Public Domain (للنسخة/الحلقة حسب المصدر)",source:"Internet Archive"},
{id:6,title:"Felix the Cat – The Magic Bag",type:"series",year:1958,genre:"رسوم متحركة • كلاسيكي",rating:7.2,tag:"Public Domain",description:"حلقة من سلسلة Felix the Cat؛ نسخة الحلقة المشار إليها متاحة في المجال العام وفق صفحة Wikimedia Commons.",poster:"linear-gradient(145deg,#312e81,#db2777)",watchUrl:"https://commons.wikimedia.org/wiki/File:001-Felix-the-Cat-S01E01-The-Magic-Bag.webm",license:"Public Domain (للنسخة المشار إليها)",source:"Wikimedia Commons"},
{id:7,title:"Big Buck Bunny – Animation",type:"anime",year:2008,genre:"رسوم متحركة",rating:8.1,tag:"مرخّص CC",description:"محتوى رسوم متحركة مفتوح من Blender Foundation. التصنيف هنا ضمن قسم الرسوم المفتوحة وليس أنميًا يابانيًا.",poster:"linear-gradient(145deg,#064e3b,#22c55e)",watchUrl:"https://video.blender.org/videos/watch/bf1f3fb5-b119-4f9f-9930-8e20e892b898",license:"Creative Commons Attribution 3.0",source:"Blender Foundation"},
{id:8,title:"Sintel – Animation",type:"anime",year:2010,genre:"فانتازيا • رسوم متحركة",rating:8.0,tag:"مرخّص CC",description:"رسوم متحركة مفتوحة من Blender Foundation. هذا العمل ليس أنميًا يابانيًا، وتم وضعه هنا مؤقتًا ضمن قسم الرسوم المفتوحة.",poster:"linear-gradient(145deg,#1e1b4b,#06b6d4)",watchUrl:"https://durian.blender.org/",license:"Creative Commons Attribution 3.0",source:"Blender Foundation"} ,
{id:9,title:"Spring",type:"movie",year:2019,genre:"فانتازيا • رسوم متحركة",rating:0,tag:"مرخّص CC BY 4.0",description:"فيلم رسوم متحركة قصير من Blender Animation Studio، منشور وفق Creative Commons Attribution 4.0 مع متطلبات النسب.",poster:"linear-gradient(145deg,#14532d,#84cc16)",embedUrl:"https://studio.blender.org/projects/spring/",license:"Creative Commons Attribution 4.0",source:"Blender Studio"},
{id:10,title:"Cosmos Laundromat: First Cycle",type:"movie",year:2015,genre:"خيال • رسوم متحركة",rating:0,tag:"مفتوح ومرخّص",description:"الحلقة الأولى من مشروع Blender Open Movie، متاحة للمشاركة وإعادة المزج وفق الترخيص المعلن للمشروع.",poster:"linear-gradient(145deg,#312e81,#f97316)",embedUrl:"https://studio.blender.org/projects/cosmos-laundromat/",license:"Creative Commons / permissive license حسب مادة المشروع",source:"Blender Studio"},
{id:11,title:"Charge",type:"movie",year:2022,genre:"خيال علمي • أكشن",rating:0,tag:"مرخّص CC BY 4.0",description:"فيلم Blender Open Movie قصير في عالم مستقبلي يعاني من نقص الطاقة؛ محتوى Blender Studio الرقمي متاح عمومًا وفق CC BY ما لم يذكر خلاف ذلك.",poster:"linear-gradient(145deg,#111827,#dc2626)",embedUrl:"https://studio.blender.org/projects/charge/",license:"Creative Commons Attribution 4.0 (ما لم يذكر خلاف ذلك)",source:"Blender Studio"},
{id:12,title:"Sprite Fright",type:"movie",year:2021,genre:"رعب كوميدي • رسوم متحركة",rating:0,tag:"مرخّص CC BY",description:"فيلم Blender Open Movie بطابع رعب كوميدي، ومشروعه منشور وفق Creative Commons Attribution مع استثناءات موضحة في صفحة الترخيص.",poster:"linear-gradient(145deg,#3f0d12,#16a34a)",embedUrl:"https://studio.blender.org/projects/sprite-fright/",license:"Creative Commons Attribution 1.0",source:"Blender Studio"},
{id:13,title:"Wing It!",type:"movie",year:2023,genre:"كوميديا • رسوم متحركة",rating:0,tag:"مرخّص CC BY 4.0",description:"فيلم Blender Open Movie قصير؛ صفحة الترخيص الرسمية تسمح بإعادة الاستخدام والتوزيع مع النسب.",poster:"linear-gradient(145deg,#0f172a,#f59e0b)",embedUrl:"https://studio.blender.org/projects/wing-it/",license:"Creative Commons Attribution 4.0",source:"Blender Studio"}
];
