window.VIP_CONTENT=[
{id:1,title:"Big Buck Bunny",type:"movie",year:2008,genre:"رسوم متحركة",rating:8.1,tag:"مرخّص CC",description:"فيلم رسوم متحركة قصير من Blender Foundation، متاح لإعادة الاستخدام وفق CC BY مع متطلبات النسب.",poster:"linear-gradient(145deg,#14532d,#f59e0b)",videoUrl:"https://video.blender.org/static/webseed/bf1f3fb5-b119-4f9f-9930-8e20e892b898-720.mp4",embedUrl:"https://video.blender.org/videos/embed/bf1f3fb5-b119-4f9f-9930-8e20e892b898",license:"Creative Commons Attribution",source:"Blender Foundation"},
{id:2,title:"Sintel",type:"movie",year:2010,genre:"فانتازيا • رسوم متحركة",rating:8,tag:"مرخّص CC",description:"فيلم قصير مفتوح من Blender Foundation. تم تحويل التشغيل إلى صفحة PeerTube الحالية بعد تقادم رابط MP4 القديم.",poster:"linear-gradient(145deg,#172554,#7c3aed)",watchUrl:"https://video.blender.org/w/2PcJe5aZqozRvH7MJ8BTmC",embedUrl:"https://video.blender.org/w/2PcJe5aZqozRvH7MJ8BTmC",license:"Creative Commons Attribution",source:"Blender Foundation"},
{id:3,title:"Elephants Dream",type:"movie",year:2006,genre:"خيال • رسوم متحركة",rating:7.8,tag:"مرخّص CC",description:"أول أفلام Blender Open Movie، منشور بترخيص Creative Commons.",poster:"linear-gradient(145deg,#3f1d0b,#ea580c)",videoUrl:"https://video.blender.org/static/webseed/cccc3e60-0291-4ecc-aa56-39b2e2c7d0d5-720.mp4",embedUrl:"https://video.blender.org/videos/embed/cccc3e60-0291-4ecc-aa56-39b2e2c7d0d5",license:"Creative Commons Attribution",source:"Blender Foundation"},
{id:4,title:"Tears of Steel",type:"movie",year:2012,genre:"خيال علمي",rating:7.7,tag:"مرخّص مفتوح",description:"فيلم مفتوح من Blender Institute؛ شروط الترخيص تختلف حسب المادة، لذلك نعرض المصدر والترخيص بوضوح.",poster:"linear-gradient(145deg,#082f49,#0891b2)",videoUrl:"https://video.blender.org/static/webseed/8533ea43-4271-4a57-9694-e9d0b35e1aa1-720.mp4",embedUrl:"https://video.blender.org/videos/embed/8533ea43-4271-4a57-9694-e9d0b35e1aa1",license:"Creative Commons (راجع شروط المشروع)",source:"Blender Foundation"},
{id:5,title:"Captain Video – Episode",type:"series",year:1949,genre:"خيال علمي • كلاسيكي",rating:7,tag:"Public Domain",description:"حلقة من Captain Video and His Video Rangers؛ صفحة Wikimedia Commons تسجلها كعمل في المجال العام في الولايات المتحدة.",poster:"linear-gradient(145deg,#111827,#2563eb)",videoUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/CaptainVideo1949.ogv",license:"Public Domain (وفق صفحة الملف؛ تحقق من بلدك)",source:"Wikimedia Commons"},
{id:6,title:"Felix the Cat – The Magic Bag",type:"series",year:1928,genre:"رسوم متحركة • كلاسيكي",rating:7.2,tag:"Public Domain",description:"رسوم متحركة كلاسيكية مع مصدر فيديو من Wikimedia Commons.",poster:"linear-gradient(145deg,#312e81,#db2777)",videoUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/001-Felix-the-Cat-S01E01-The-Magic-Bag.webm",license:"Public Domain (للنسخة المشار إليها)",source:"Wikimedia Commons"},
{id:9,title:"Spring",type:"movie",year:2019,genre:"فانتازيا • رسوم متحركة",rating:0,tag:"مرخّص CC BY 4.0",description:"فيلم رسوم متحركة قصير من Blender Animation Studio، منشور وفق Creative Commons Attribution 4.0.",poster:"linear-gradient(145deg,#14532d,#84cc16)",videoUrl:"https://video.blender.org/static/webseed/3d95fb3d-c866-42c8-9db1-fe82f48ccb95-720.mp4",embedUrl:"https://video.blender.org/videos/embed/3d95fb3d-c866-42c8-9db1-fe82f48ccb95",license:"Creative Commons Attribution 4.0",source:"Blender Studio"},
{id:11,title:"Charge",type:"movie",year:2022,genre:"خيال علمي • أكشن",rating:0,tag:"مشروع Blender",description:"محتوى من مشروع Charge في Blender Studio. نستخدم صفحة الفيديو الرسمية داخل المشغل بدلاً من صفحة المشروع.",poster:"linear-gradient(145deg,#111827,#dc2626)",embedUrl:"https://video.blender.org/videos/embed/09f77c81-7b1b-483a-9d46-b14f2078c604",license:"تحقق من شروط المادة قبل إعادة الاستخدام",source:"Blender Studio"},
{id:12,title:"Sprite Fright",type:"movie",year:2021,genre:"رعب كوميدي • رسوم متحركة",rating:0,tag:"مرخّص CC BY",description:"فيلم Blender Open Movie بطابع رعب كوميدي. مشروعه منشور وفق Creative Commons Attribution مع استثناءات موضحة رسمياً.",poster:"linear-gradient(145deg,#3f0d12,#16a34a)",videoUrl:"https://video.blender.org/download/videos/a69d68a5-a0e0-4a80-9d66-49f093c97aaf-720.mp4",embedUrl:"https://video.blender.org/videos/embed/a69d68a5-a0e0-4a80-9d66-49f093c97aaf",license:"Creative Commons Attribution 1.0",source:"Blender Studio"},
{id:14,title:"Wing It!",type:"movie",year:2023,genre:"كوميديا • رسوم متحركة",rating:0,tag:"مرخّص CC BY 4.0",description:"فيلم Blender Open Movie قصير، مرخّص وفق Creative Commons Attribution 4.0 مع الالتزام بالنسب.",poster:"linear-gradient(145deg,#0f172a,#f59e0b)",embedUrl:"https://video.blender.org/videos/embed/bd0084a5-1d26-4816-ab5e-1bad9e2fb990",license:"Creative Commons Attribution 4.0",source:"Blender Studio"},
{id:15,title:"Felix the Cat – Kept on Walking",type:"anime",year:1925,genre:"رسوم متحركة • كلاسيكي",rating:0,tag:"Public Domain",description:"رسوم متحركة كلاسيكية من 1925؛ الملف في Wikimedia Commons موسوم Public Domain في الولايات المتحدة.",poster:"linear-gradient(145deg,#18181b,#eab308)",videoUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Felix_the_Cat_Kept_on_Walking_%281925%29.webm",license:"Public Domain (وفق Wikimedia Commons؛ تحقق من بلدك)",source:"Wikimedia Commons"},
{id:16,title:"Felix the Cat – Stone Age",type:"anime",year:1922,genre:"رسوم متحركة • كلاسيكي",rating:0,tag:"Public Domain",description:"رسوم متحركة قصيرة من 1922، وملف الفيديو في Wikimedia Commons موسوم Public Domain.",poster:"linear-gradient(145deg,#27272a,#f97316)",videoUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Felix_The_Cat_1922_The_Stone_Age.webm",license:"Public Domain (وفق Wikimedia Commons؛ تحقق من بلدك)",source:"Wikimedia Commons"},
{id:17,title:"Felix the Cat – Uncle Tom's Crabbin",type:"anime",year:1927,genre:"رسوم متحركة • كلاسيكي",rating:0,tag:"Public Domain",description:"رسوم متحركة قصيرة من 1927؛ ملف الفيديو في Wikimedia Commons موسوم Public Domain.",poster:"linear-gradient(145deg,#3f3f46,#84cc16)",videoUrl:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Felix_The_Cat_Uncle_Tom%27s_Crabbin_%281927%29.webm",license:"Public Domain (وفق Wikimedia Commons؛ تحقق من بلدك)",source:"Wikimedia Commons"}
];