const $=s=>document.querySelector(s);let client=null,channels=[],matches=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){if(!window.supabase)return fail('Supabase غير متوفر.');client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await client.auth.getSession();if(!session)return fail('سجل الدخول أولاً.');const {data:admin,error}=await client.from('vip_admins').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!admin)return fail(error?'تعذر التحقق: '+error.message:'هذا الحساب ليس مديراً.');await load();}
function fail(msg){document.body.innerHTML='<main class="admin"><div class="notice">'+esc(msg)+'</div><a class="btn primary" href="login.html">تسجيل الدخول</a></main>'}
async function load(){const [c,m]=await Promise.all([client.from('vip_live_channels').select('*').order('sort_order').order('name'),client.from('vip_live_matches').select('*').order('start_time',{ascending:true})]);if(c.error||m.error)return fail('تعذر تحميل بيانات البث: '+esc(c.error?.message||m.error?.message));channels=c.data||[];matches=m.data||[];drawChannels();drawMatches();}
function drawChannels(){$('#channelRows').innerHTML=channels.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.category)+'</td><td>'+(x.is_live?'🔴':'—')+'</td><td>'+(x.published?'✓':'مسودة')+'</td><td><button class="btn small ghost" onclick="editChannel('+Number(x.id)+')">تعديل</button> <button class="btn small danger" onclick="removeChannel('+Number(x.id)+')">حذف</button></td></tr>').join('')||'<tr><td colspan="5" class="muted">لا توجد قنوات.</td></tr>'}
function resetChannel(){['channelId','channelName','channelDescription','channelLogo','channelStream','channelEmbed','channelSource','channelLicense','channelRights'].forEach(id=>$('#'+id).value='');$('#channelCategory').value='general';$('#channelLanguage').value='ar';$('#channelTerritories').value='Worldwide';$('#channelOrder').value='0';$('#channelLive').checked=false;$('#channelPublished').checked=false}
window.editChannel=id=>{const x=channels.find(v=>Number(v.id)===Number(id));if(!x)return;$('#channelId').value=x.id;$('#channelName').value=x.name;$('#channelCategory').value=x.category;$('#channelLanguage').value=x.language||'ar';$('#channelDescription').value=x.description||'';$('#channelLogo').value=x.logo_url||'';$('#channelStream').value=x.stream_url||'';$('#channelEmbed').value=x.embed_url||'';$('#channelSource').value=x.source_url||'';$('#channelLicense').value=x.license_url||'';$('#channelRights').value=x.rights_holder||'';$('#channelTerritories').value=x.territories||'Worldwide';$('#channelOrder').value=x.sort_order||0;$('#channelLive').checked=x.is_live;$('#channelPublished').checked=x.published;scrollTo(0,0)}
$('#channelReset').onclick=resetChannel;
$('#channelForm').onsubmit=async e=>{e.preventDefault();const payload={name:$('#channelName').value.trim(),category:$('#channelCategory').value,language:$('#channelLanguage').value.trim()||'ar',description:$('#channelDescription').value.trim()||null,logo_url:$('#channelLogo').value.trim()||null,stream_url:$('#channelStream').value.trim()||null,embed_url:$('#channelEmbed').value.trim()||null,source_url:$('#channelSource').value.trim()||null,license_url:$('#channelLicense').value.trim()||null,rights_holder:$('#channelRights').value.trim()||null,territories:$('#channelTerritories').value.trim()||'Worldwide',sort_order:Number($('#channelOrder').value)||0,is_live:$('#channelLive').checked,published:$('#channelPublished').checked,updated_at:new Date().toISOString()};if(!payload.license_url)return alert('أضف رابط إثبات الحقوق/الترخيص.');if(!payload.stream_url&&!payload.embed_url)return alert('أضف رابط Stream أو Embed.');const id=Number($('#channelId').value||0);const r=id?await client.from('vip_live_channels').update(payload).eq('id',id):await client.from('vip_live_channels').insert(payload);if(r.error)return alert(r.error.message);resetChannel();await load();}
window.removeChannel=async id=>{if(!confirm('حذف القناة؟'))return;const r=await client.from('vip_live_channels').delete().eq('id',id);if(r.error)return alert(r.error.message);await load()};
function resetMatch(){['matchId','league','homeTeam','awayTeam','homeLogo','awayLogo','startTime','minute','venue','matchStream','matchEmbed','matchSource','matchLicense','matchRights'].forEach(id=>$('#'+id).value='');$('#matchStatus').value='scheduled';['homeScore','awayScore','posH','posA','shotsH','shotsA','sotH','sotA','cornH','cornA','yellowH','yellowA','redH','redA'].forEach(id=>$('#'+id).value='0');$('#matchTerritories').value='Worldwide';$('#matchPublished').checked=false}
window.editMatch=id=>{const x=matches.find(v=>Number(v.id)===Number(id));if(!x)return;$('#matchId').value=x.id;$('#league').value=x.league||'';$('#homeTeam').value=x.home_team;$('#awayTeam').value=x.away_team;$('#homeLogo').value=x.home_logo||'';$('#awayLogo').value=x.away_logo||'';$('#matchStatus').value=x.status;$('#startTime').value=x.start_time?new Date(x.start_time).toISOString().slice(0,16):'';$('#homeScore').value=x.home_score;$('#awayScore').value=x.away_score;$('#minute').value=x.minute??'';$('#venue').value=x.venue||'';$('#matchStream').value=x.stream_url||'';$('#matchEmbed').value=x.embed_url||'';$('#matchSource').value=x.source_url||'';$('#matchLicense').value=x.license_url||'';$('#matchRights').value=x.rights_holder||'';$('#matchTerritories').value=x.territories||'Worldwide';[['posH',x.possession_home],['posA',x.possession_away],['shotsH',x.shots_home],['shotsA',x.shots_away],['sotH',x.shots_on_target_home],['sotA',x.shots_on_target_away],['cornH',x.corners_home],['cornA',x.corners_away],['yellowH',x.yellow_home],['yellowA',x.yellow_away],['redH',x.red_home],['redA',x.red_away]].forEach(([id,v])=>$('#'+id).value=v??0);$('#matchPublished').checked=x.published;scrollTo(0,500)}
$('#matchReset').onclick=resetMatch;
$('#matchForm').onsubmit=async e=>{e.preventDefault();const payload={league:$('#league').value.trim()||null,home_team:$('#homeTeam').value.trim(),away_team:$('#awayTeam').value.trim(),home_logo:$('#homeLogo').value.trim()||null,away_logo:$('#awayLogo').value.trim()||null,status:$('#matchStatus').value,start_time:$('#startTime').value?new Date($('#startTime').value).toISOString():null,home_score:Number($('#homeScore').value)||0,away_score:Number($('#awayScore').value)||0,minute:Number($('#minute').value)||null,venue:$('#venue').value.trim()||null,stream_url:$('#matchStream').value.trim()||null,embed_url:$('#matchEmbed').value.trim()||null,source_url:$('#matchSource').value.trim()||null,license_url:$('#matchLicense').value.trim()||null,rights_holder:$('#matchRights').value.trim()||null,territories:$('#matchTerritories').value.trim()||'Worldwide',possession_home:Number($('#posH').value)||0,possession_away:Number($('#posA').value)||0,shots_home:Number($('#shotsH').value)||0,shots_away:Number($('#shotsA').value)||0,shots_on_target_home:Number($('#sotH').value)||0,shots_on_target_away:Number($('#sotA').value)||0,corners_home:Number($('#cornH').value)||0,corners_away:Number($('#cornA').value)||0,yellow_home:Number($('#yellowH').value)||0,yellow_away:Number($('#yellowA').value)||0,red_home:Number($('#redH').value)||0,red_away:Number($('#redA').value)||0,published:$('#matchPublished').checked,updated_at:new Date().toISOString()};if(!payload.license_url)return alert('أضف رابط إثبات الحقوق/الترخيص للمباراة أو البث.');const id=Number($('#matchId').value||0);const r=id?await client.from('vip_live_matches').update(payload).eq('id',id):await client.from('vip_live_matches').insert(payload);if(r.error)return alert(r.error.message);resetMatch();await load();}
window.removeMatch=async id=>{if(!confirm('حذف المباراة؟'))return;const r=await client.from('vip_live_matches').delete().eq('id',id);if(r.error)return alert(r.message);await load()}
function drawMatches(){$('#matchRows').innerHTML=matches.map(x=>'<tr><td>'+esc(x.home_team)+' × '+esc(x.away_team)+'</td><td>'+esc(x.status)+'</td><td>'+Number(x.home_score||0)+' - '+Number(x.away_score||0)+'</td><td>'+(x.published?'✓':'مسودة')+'</td><td><button class="btn small ghost" onclick="editMatch('+Number(x.id)+')">تعديل</button> <button class="btn small danger" onclick="removeMatch('+Number(x.id)+')">حذف</button></td></tr>').join('')||'<tr><td colspan="5" class="muted">لا توجد مباريات.</td></tr>'}
init();